### ISSUE TITLE
Start lag

### ISSUE THREAD

**Issue by ImDxni** [SQuazar/OfflineManager#8]
the init() method in the Storage class would take too much time in server with a lot of players, i tried it in mine and every time i try to load the plugin it blocks the main thread for about 40 seconds

**Comment by SQuazar** [comment]
Try this and post the result
[OfflineManager.zip](https://github.com/SQuazar/OfflineManager/files/9275701/OfflineManager.zip)
.

**Comment by SQuazar** [comment]
Use **async-storage-init** in 3.0.9 version.
