### ISSUE TITLE
File is broken

### ISSUE THREAD

**Issue by Serega007RU** [SQuazar/OfflineManager#9]
Здравствуйте. Используем ваш плагин на сервере с модами, а точнее на ядре Mohist.
Всё работает, но есть большой спам ошибок при запуске сервера
![image](https://user-images.githubusercontent.com/64780091/205513397-241c9d36-b5dc-4b80-bbd4-c461758190a0.png)
Он ругается на файлы которые сохраняет мод CyclicMagic. Можно что б он игнорировал эти файлы?

Если вы смотрите по всем файлам что есть в дирректории playerdata, то вот в каких форматах ещё моды могут хранить файлы
`0005d8d1-41dc-7d89-d6f1-d4fd6e9c2aeb.cosarmor`
`0005c5ba-d868-cdc3-cdd2-fb604be73d74.cyclicinvo`
`Serega007.thaum`
`Serega007.thaumback`
`Serega007.baubback`
`Serega007.baub`
`0bcd2b64-4c81-11ed-8a4e-001c424d49c9.astral`
`0bcd2b64-4c81-11ed-8a4e-001c424d49c9.astralback`
Думаю я тут далеко не всё перечислил, это всё что я нашёл у себя на серверах)

Версия плагина 3.0.7
Версия Mohist (Forge 1.12.2 + Bukkit) 1.12.2-320

**Comment by SQuazar** [comment]
Добавил новый параметр в конфигурацию плагина https://github.com/SQuazar/OfflineManager/commit/4c89213e7bc75983e306b00c2b6181fccf341379
Ожидайте новую версию в релизах.
